name: Build and deploy Zola to FTP

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure all submodules are fetched
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure all submodules are fetched
      - name: Build Zola site
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ./
          protocol: ftps
          # See https://github.com/SamKirkland/FTP-Deploy-Action/issues/146
          state-name: ../.ftp-deploy-sync-state.json
          log-level: verbose
