name: Build and deploy Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure all submodules are fetched
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure all submodules are fetched
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
